### ISSUE TITLE
Suggestion: Allow check code to be written in an external file or module/package

### ISSUE THREAD

**Issue by amoeba** [NCEAS/mdqengine#10]
Writing check code inside XML seems unwieldy, especially given that I can't write correct Python or R code without trying it out, which is substantially easier when I'm in a dedicated Python or R buffer in my editor.

Suggestion: Allow a 'check library' for each suite and then each `<check>` element would reference routines in that suite.

Benefits:

- It's hard to write valid code without testing it out
  - Check writer can run a linter over code to ensure it works
  - Check writer can run the code against dummy variables to make sure it works
  - Check writer's text editor can help format and syntax highlight code which makes it easier to write for some people

Downsides:

- Checks become harder to understand at a glance because a separate file is needed to understand what the check entails

## Example API

```
.
|-- suite.xml
|-- suite.R
```

suite.xml

```{xml}
<suite>
  ...
  <library> <!-- bad name? -->
    suite.R <!-- rel. file path -->
  </library>
  <check>
    ...
    <environment>r</environment>
    <function>some_check</function>
    <selector>
      <name>entityCount</name>
      <xpath>count(/eml/dataset/dataTable)</xpath>
    </selector>
  </check>
  ...
</suite>
```

suite.R

```{R}
some_check <- function() {
  entitycount would be available here
}
```

Notes:

- Checks can still specify code in-line
- Prior to running the check, the MQE would load the function the check specifies and call it with the names the check specifies xpaths for

Alternatives:

- Each check function could be a separate file
- The check functions could be a package unto themselves

@gothub How has writing your more complex checks felt using the current API?

**Comment by amoeba** [comment]
Alternative choices include,

- In-lining code (status quo)
- Single file per suite, checks reference names from within that document
- Single snippet file per check
- R or Python package per suite, checks reference the package

[[editing this as we talk]]

**Comment by leinfelder** [comment]
There's now check.library that allows you to point to a URL where your extra code is housed. First the library content will be interpreted, then the code block, if any, will be executed.
