### ISSUE TITLE
Define a suite XML schema and validate the suite XML prior to running

### ISSUE THREAD

**Issue by amoeba** [NCEAS/mdqengine#11]
Is there any benefit to having a schema and validating the suite XML files prior to running? When a suite is run and it fails to run due to the suite XML, it would be really great to have useful errors. Schema validation would be one way to achieve this. An alternative would be to hoist a lot of checking into the Java code.

~~Have we talked about this yet?~~We talked about it here.

- [ ] Create a Suite schema
- [ ] Check suites against the schema prior to running

**Comment by leinfelder** [comment]
Yes, I fully intend to have a schema. I haven't written one since it seemed like we were still hashing through the model and pictures are easier to communicate with.
JAXB would do the validation as part of the deserialization.

**Comment by amoeba** [comment]
Great! Decided.

Shall I leave this ticket open so we can track progress on this? I'll rename it to remove the 'Suggestion' from the title.

**Comment by leinfelder** [comment]
We are now generating a schema from the Java object model using JAXB annotations and a nifty maven plugin. The schema is included in the library resources and used when unmarshalling XML to ensure it is valid.
