### ISSUE TITLE
Document guidelines for using the quality engine

### ISSUE THREAD

**Issue by gothub** [NCEAS/mdqengine#16]
Create a markdown document that describes how to develop checks, and use mdqe:

Some of the points to cover:
* creating a check configuration
  * brief description of all check configuration elements
  * how to use selectors and subselectors 
  * using the inherited state from one check to another
* registering and testing checks
  * registering a check with an instance of the quality engine
  * testing and debugging a quality check
* running / creating reports for suites and individual checks

What else?

**Comment by amoeba** [comment]
Good idea. I'd add:

- High level overview of how the engine runs checks which should help authors write checks
- How to get and share data between checks (new feature)

**Comment by amoeba** [comment]
I accidentally created a dupe ticket in #33. Closed that one and copied content here:

- Writing suites
  - ids
- Writing one-off checks and including them in suites
- Check that returns a count
- Check that an element exists
- Check that checks a concept across dialects
- Outputs
- Check levels
- Check statuses
- Check types
- More?

**Comment by amoeba** [comment]
- Don't use namespace prefixes in xpaths

**Comment by leinfelder** [comment]
Added getting started guide to main README
