### ISSUE TITLE
Implement cross-environment data caching

### ISSUE THREAD

**Issue by leinfelder** [NCEAS/mdqengine#17]
In issue #2, there was a request to allow data files to be cached locally by checks so that other checks  need not download them directly from their remote location.

My proposal is to have these script "libraries": 

- [x] mqd-cache.R
- [x] mdq-cache.js
- [x] mdq-cache.py
- [x] MDQCache.java 

Each environment can then use the shared caching system like:
`String dataPath = MDQCache.get(url); // either returns it from local store, or fetches it from URL and saves for future retrieval`

**Comment by gothub** [comment]
@leinfelder This looks great. I'll update the dreaded LTER test suite to use this. Also, I'll add a unit test that checks the translation of data types between languages, i.e. R data.frame to Python list of lists, etc.

**Comment by leinfelder** [comment]
Peter, you will only get a file path (String) back from the cache and it will be up to the check code to actually read it from disk into the structure that it wants.

Also, this is not implemented yet, so I'd hold off on changing the LTER suite until we are happy with a version of the cache.

**Comment by amoeba** [comment]
what are the properties of the caching system?

- all cached files are read only?
- works across environments within a suite run?
- if another suite run wants to `get()` an already cached file, would it get it from cache? i.e. do all running suites share a cache?
- we just clean the cache ~daily?

**Comment by gothub** [comment]
Is it possible to make the http response header info available from the download of a file
in the cache? The checks could use this info, such as "Content-Type" and "Content-Encoding"?

**Comment by amoeba** [comment]
R version implemented in d579399af543f79df1d7fe864c89cbae7f03e76f.
