### ISSUE TITLE
Inclue QC viz in Metacat UI

### ISSUE THREAD

**Issue by leinfelder** [NCEAS/mdqengine#18]
Issue #15 exposes an endpoint for plotting a single document's QC. For example, here's partial curl command for getting it as an SVG:

`curl -X POST /suites/{id}/plot --form "document=@path/to/metadata/doc.xml -H "Accept: application/svg+xml"`

PNG and PDF are also currently supported.

I'd like to have the result displayed in Metacat UI - perhaps as a modal viewer? - when a user clicks a "view QC report" button. Or something. I'm very open to suggestions.

**Comment by amoeba** [comment]
Don't suite runs need to be cached? And then shouldn't visualizations be powered by that cache? Or is this just a temporary way to play around?

**Comment by leinfelder** [comment]
Either, both. If we can visualized a Run or a set of runs then it doesn't much matter if they are generated on the fly or read from a persistent repo

**Comment by leinfelder** [comment]
But, yes, playing around for now

**Comment by leinfelder** [comment]
Done!
