### ISSUE TITLE
Using R variable name 'result' causes check to fail

### ISSUE THREAD

**Issue by gothub** [NCEAS/mdqengine#21]
`RDispatcher` uses the R variable name `result` internally for the cache mechanism. If a check uses this variable name, then the check fails with the error:

```
 20160728-06:27:54: [DEBUG]: result value: null [edu.ucsb.nceas.mdqengine.PreTest]
20160728-06:27:54: [DEBUG]: result message: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $ [edu.ucsb.nceas.mdqengine.PreTest]
```

The check code that caused the error:
```
                <code><![CDATA[
check <- function() {
    status <- "SUCCESS"
    message <- "The packageId is valid"
    # ... do some checks here, set status, message ...
    return(list(status, message))
}

result <- check()
status <- result[[1]]
message <- result[[2]]
TRUE
      ]]></code>
```

**Comment by leinfelder** [comment]
It is not the cache mechanism (which actually isn't implemented using the "rscripit" env yet) but that you have assigned your result variable the wrong structure. You have set result to be a list, not an object. The error message indicates this as well.
Your method should return this:
`return list(status=status, message=message, value=<someValue>)`

NB: In an effort to make it easy for the check writer, the RDispatcher will create a correct result structure with the last value set as result.value.

**Comment by leinfelder** [comment]
Thinking about this a little more, I can see how it is confusing. The other engines don't assume a Result object is returned. But maybe they should?

**Comment by gothub** [comment]
We are using variables in each scripting language to communicate check state back to the scripting engine, which is great. I'd like to re-consider the names that we use so that it is totally obvious to check writers that these variables are related to mdqe and not common names. Currently we have:

- status : to communicate a check status
- message : a description of the check result
- result: the result of the check for Rscript checks

Maybe all scripting languages could each return just `mdqe.status` and `mdqe.message` from
checks and not result (or result.value)?

**Comment by leinfelder** [comment]
Okay, I've adjusted the expectations of the Dispatcher and added a few more tests to exercise the return of Result objects. I also converted the LTER "r" tests to use the newer "rscript" implementation rather than renjin. I think we will phase out renjin soon.
