### ISSUE TITLE
Support rich content in Results

### ISSUE THREAD

**Issue by amoeba** [NCEAS/mdqengine#24]
Results can currently store values as Strings. If a check also wants to save a plot, for example, we need to modify the Result model a bit. Use cases I can think of would be supporting checks to save:

- Tabluar data (e.g. R/pandas data.frames)
- Image data (e.g. a PNG or an R gg object)

as a value. I think these are core use cases.

For the PNG example, we could base64 encode the PNG, throw it in the serialized Result XML and pair it with a mime type of `image/png`. We could the same thing with a CSV and use the `text/csv` mime type.

**Comment by amoeba** [comment]
What could the check API look like for this? For each value, we need the bytes and the mime type?

**Option: Make the check base64 encode the object(s)?**

```{R}
library(base64enc)

myobject # a data.frame


# result would be a list
results[[1]] <- list(mime = 'text/csv', value = base64enc(myobject))
results[[2]] <- list(mime = 'text/csv', value = base64enc(myobject))
results[[3]] <- list(mime = 'text/csv', value = base64enc(myobject))
results[[4]] <- list(mime = 'text/csv', value = base64enc(myobject))
results[[5]] <- list(mime = 'text/csv', value = base64enc(myobject))
```

**Option: Do magic on the values to guess mime type?**

```{r}
library(base64enc)

myobject # a data.frame

# results could be a char-vector or list
results[1] <- base64enc(myobject)
results[2] <- base64enc(myobject)
results[3] <- base64enc(myobject)
results[4] <- base64enc(myobject)
results[5] <- base64enc(myobject)
```

**Option: Do magic on the entire value?**

```{r}
myobject # a data.frame

# results would be a list
results[1] <- myobject
```

In the last example, the engine would the need to:

- Detect the type of `myobject`
- Encode the object
- Set the mime type

This seems reasonable. If the type of the object being saved were a data.frame or matrix, it could be converted to a CSV and encoded. Simpler base types such as vectors and lists could be pretty printed and serialized as text.

Capturing plots is a little trickier. Base R plots appear to be capturable but it doesn't look pretty. ggplot2 graphics can be saved to variables easily. We could target both if we made the check write the plot to disk. If the graphic was a ggplot2 graphic we could handle all of that for them.

**Comment by mbjones** [comment]
I agree on principle with this, but would qualify it that we should really only be dealing in *relatively* open formats, such as text, csv, png, etc.  A system specific format like an R gg object is not a reasonable return value from a check.  I think a good litmus test would be whether a standard Chrome of Firefox browser knows how to render that object if it were embedded in an html document.

**Comment by amoeba** [comment]
What would the serialized Result XML look like? Something like?

```{xml}
....
    <values>
      <value type='text/csv'><![CDATA[
       my,csv,header,line
       1,2,3,4
       ]]>
      </value>
      <value type='image/png'><![CDATA[
       {{base64 encoded png as ASCII text}}
       ]]>
      </value>
    </values>
....
```

**Comment by amoeba** [comment]
@mbjones you wrote:

>  A system specific format like an R gg object is not a reasonable return value from a check. 

Why not? The engine could just convert it for the user. Same goes for a data.frame. I'd much rather write an INFO check like:


```{r}
library(ggplot2)
ggplot(...) ## gg object is automatically captured and converted
```

than

```{r}
library(ggplot2)
library(base64encode)

g <- ggplot(...)
tmp <- tempfile(ext='.png')
ggsave(tempfile, g) # saves png to disk
tmp_enc <- base64encode(tmp)
file.remove(tmp)

results[[1]] <- list(type = 'text/png', tmp_enc) # sets file path as result value
```

Where in the latter example I have to manage temporary files (creating and cleaning up) and base64 encoding.

But we don't need to hyperoptimize around the check code API so I'm okay with a middle ground between my two examples.

**Comment by mbjones** [comment]
Yeah, I don't think the check code should need to do the base 64 encoding -- that's up to the engine.  But the engine shouldn't have to know about language-specific data formats to get it represented.  For example, whatever is returned from a check should be equally accessible to python, java, and R, and the engine can then figure out how to encode it in the report.  It will be really hard for the java engine to deal with R-specific objects without launching another R engine.  So, here's a middle ground for your example:

```{r}
library(ggplot2)
g <- ggplot(...)
tmp <- tempfile(ext='.png')
ggsave(tmp, g) # saves png to disk
results[[1]] <- list(type = 'text/png', tmp_enc) # sets file path as result value
```

Although that is probably dangerous code as the temp file might get removed when the r session ends.  Probably need to think through the persistence issues across processes a bit.

**Comment by amoeba** [comment]
> But the engine shouldn't have to know about language-specific data formats to get it represented. 

I like that line.


How does the engine know it needs to encode `tmp`? For some files, we won't want to encode them and for some we will?

**Comment by mbjones** [comment]
Mime type, presumably?

**Comment by amoeba** [comment]
Sounds good to me!

**Comment by leinfelder** [comment]
Speaking in litmus tests, a way to consider what a check returns such that another check (in a different language) can use the values it sets up/returns is to see if it can reasonably be serialized a JSON. I agree that we can't - and don't really want to be - passing around complex language-specific objects.

@amoeba, perhaps our R "post code" could handle the mime-typing and encoding of complex objects so that your check code can remain relatively straight-forward. Or we could do what @mbjones suggested and have the engine look for file paths in the Result.value/values and encode them as needed. I guess we can do both, conditionally. "Found a file path? Yes! "Binary? Encode it! Text of some sort? Yes! Read it from disk into the 'value' element"

@mbjones, for temp files, we could be very explicit about it such that the engine creates a unique temp directory each time it runs a suite such that every check in the suite "knows" the location and can use it during the entire suite execution, and the temp dir is deleted only when the suite has completed. 
This would actually be very useful for our current RDispatcher since the way we are getting variable in and out of "rscript" executions is to serialize a) the script to run, b) the input variables as JSON, c) the output Result object as JSON, and d) (soon) the output variables as JSON. Most of these get cleaned up already when the check completes, but the output variables obviously can't be if they are meant for a downstream check to utilize...

**Comment by amoeba** [comment]
- I think automatically "doing the right thing" when the result value is a file path makes the most sense, would be easy to implement, and present a good API. I could do that.
- I think having a run-specific temp dir makes a ton of sense!

**Comment by gothub** [comment]
I'm kinda joining this party late, so I'm just wondering how returning rich content from a check
fits into our current [use cases[(https://github.com/NCEAS/metadig/blob/master/mdqengine/docs/use-cases/metadig-use-cases.csv). How does returning a CSV or graphic from a check provide more info about how a metadata document conforms to a recommendation? Are we trying to do more than that? An example would really help. Maybe we need more detail in the use cases?

**Comment by leinfelder** [comment]
Thank you Peter-the-voice-of-reason!

**Comment by leinfelder** [comment]
See issue #25 for how this will be included using: Result.output[n].value and Result.output[n].type

**Comment by leinfelder** [comment]
Done!
