### ISSUE TITLE
Support multiple result values per check

### ISSUE THREAD

**Issue by amoeba** [NCEAS/mdqengine#25]
It would very helpful if an individual check could save multiple values such as multiple `head(my_data_frame)` calls or multiple images. This relates to #24. For example, a check could be written that saves the first ten rows of every EML otherEntity for the data manager to review.

**Comment by gothub** [comment]
We discussed this earlier in regard to `message` for congruency checks where a dataset has
multiple entities, and the solution back then was to paste all the messages together. I really like
your idea of having the ability to return multiple values, but we need to consider what the quality engine is going to do with them, for example, on a detailed report for a single dataset.

**Comment by leinfelder** [comment]
Decided on updated Result mode:
Result.output (list) where output has a "value" and an optional "type" attribute.

**Comment by leinfelder** [comment]
Laying the groundwork by refactoring engine and model attribute names before changing the structure  to handle lists.

**Comment by leinfelder** [comment]
@amoeba Can you take a look at the multiple layers of list(...) that I had to do in order to make the Result.output[n].value structure? Thanks!

**Comment by amoeba** [comment]
That's how it's done, nice work!

**Comment by leinfelder** [comment]
It's a list, it's a hash, no it's a list this time!

**Comment by leinfelder** [comment]
This is done
