### ISSUE TITLE
Result object for multiple data entities

### ISSUE THREAD

**Issue by gothub** [NCEAS/mdqengine#3]
Checks can currently return information via the variables 'shared' between the check code
and the quality engine Java code: 'status', 'message' and the return value itself.

In the case of entity 'congruency' checks, a check run against a single metadata file can
run checks against multiple data entities, for example, "knb-lter-sbc-1001-7.xml" has the
dataTables "LTER01_CTD_downcasts.txt", "LTER01_CTD_upcasts.txt" and "LTER01_CTD_bottledata.txt".

How can a check return multiple values to the quality engine, i.e. the 'status' for each data entity,
the name of each entity. This return mechanism has to be known to the mqe so that it can 
be properly sorted / collated into a quality report.

**Comment by leinfelder** [comment]
Well, our model only has a single result per check whereas the LTER report kind of proliferates a variable number of "results" depending on how many entities there are in the given metadata description.

My first inclination is to keep our model as is and not report on each individual entity like LTER does. Instead, a test like "entityNameLength" would iterate through the entity names, and report an error/warning if it found one or more names that did not meet the criteria specified in the test. We could either continue checking each entity name and add to the message each value that did not match or simply stop the check on the first failure.

For something like "displayFirstInsertRow" it gets a little more murky, but I don't see why a single string couldn't capture the information for each entity, it's just organized differently than the LTER report.

**Comment by gothub** [comment]
I think that the congruency checks should check and report on all data entities, regardless of
one of them having problems. As a data manager i'd want to know about them all, so that I can
fix all problems in one go. Here I'm referring to checking metadata / data that is already archived. In
the case checking metadata that is being edited / entered, there may be reasons to 'fail fast', but
not really sure about this.

**Comment by amoeba** [comment]
Bringing up failure behavior is a good thing! However I think failing fast is probably not what users want for their recommendation runs. A check writer would ideally want their checks to report all errors (i.e. issues with all the entities, not just the first entity that failed to meet the criterion of the check). But a check writer could totally make their check fail fast and report just the first issue the check encountered. Supporting both (1) could lead to confusion for check writers on how to write checks but (2) could appease a wider audience because we aren't specifying check behavior -- they are.

**Comment by amoeba** [comment]
Example of a check accumulating errors:

names:
- otherEntities (from /eml/dataset/otherEntity)

```{r}

status <- TRUE # by default
messages <- c() # accumulates messages

for (oe in otherEntiies) {
  oe_name <- get_other_entity_name(oe) # Human-readable name for OE
  result <- check_other_entity_for_something(oe) # Some check, like "has a data url"

  if (!result)  status <- FALSE # Make check fail if any oE fails the test
  messages <- c(message, 
                ifelse(result, 
                       paste0(oe_name, " passed"), 
                       paste0(oe_name, " failed)))

}

message <- paste(messages, collapse = "; ")
```

**Comment by gothub** [comment]
@amoeba Yes, good idea - the congruency checks in the test LTER suite are now using this convention of returning info for all problematic entities in the `message` variable, identified by entity name, so that the person reading the suite report has enough info to correct the problem.
