### ISSUE TITLE
Add functionality to the R helper lib

### ISSUE THREAD

**Issue by amoeba** [NCEAS/mdqengine#30]
I'm running through the LTER suite to see where I can improve the error messages and I will write down common patterns that would be good to bundle into helper functions so checks can use them.

- [x] Element presence, e.g., title, abstract, keyword(s)

**Comment by gothub** [comment]
@amoeba How are you envisioning that the helper library will be made available to the
checks? Seems like there should be an implementations for each language:

- Java
   - include the library classes in the mdqengine-1.0.0.jar
- R 
   - source R files from the deployed dir?
   - installed library?
- Python
  - imported package
- Javascript
   - ?

**Comment by mbjones** [comment]
I prefer the installed package route, especially for R.  Bryce and I discussed this last week, and how a package would allow users to install and use the utilities locally without the engine like you can with `testthat`.  I'm not sure about the other languages, but my inclination would be the same for python.

**Comment by amoeba** [comment]
I'm leaning toward package.

Right now, the engine supports sourcing a script before running the check (check.library) so we can start there.

However, a package gives us a few things that I think are worthwhile:

- We can actually have tests for our helper lib
- (as @mbjones said), We can put the helper functions in a larger package that allows checks written in R to be run locally
- Packaging is the most straightforward way of avoiding name collision in R/Python/JS when helper lib names collide with check code names

Are there any downsides or upsides we're not thinking about?

**Comment by leinfelder** [comment]
Downside: I am always getting errors about libs that I have not yet installed. It is annoying, but not the end of the world.

**Comment by amoeba** [comment]
That's important to me too! 👍  Thanks

**Comment by amoeba** [comment]
This is done,

- The metadig R package needs to be installed on the machine running th Engine
- A check then uses:

```{r}
check_presence(some_selector_name)
```
