### ISSUE TITLE
Package level checks

### ISSUE THREAD

**Issue by gothub** [NCEAS/mdqengine#4]
The mqe has a mechanism for package level checks, i.e. an ORE pid is supplied to the engine
and it provides the metadata document and urls of data entities contained in that package.

Is this mechanism going to remain the the mqe, or will it be dropped in favor of
metadata level checks?

PS - this is somewhat a duplicate of https://github.com/NCEAS/mdqengine/issues/2, but just
want to be explicit about this.

**Comment by leinfelder** [comment]
I was thinking of removing the package support since I don't think we have an immediate use case where we would send the engine a list of ORE pids. I'm open to either, but the current implementation is a bit crude in that it tries to parse EVERY inputstream as an ORE first and then falls back to metadata if there is an error (which is usually the case).

**Comment by amoeba** [comment]
I thought every recommendation run was run on a metadata object, not a package. Is this not what we're doing?

For a recommendation run to know anything about a "package", the check writer would have to encode that knowledge in their checks and possibly have their metadata reference the "package" in some way. For example, say we were writing a recommendation for KNB metadata. I could write a check called 'otherEntity and ORE congruency check', which checked that the set of otherEntity elements in the EML had a corresponding named individual in the ORE. The check would go something like this:

names:
- packageId from /eml@packageId
- otherEntities from /eml/dataset/otherEntity

```{r}
mn <- dataone::MNode(...)
rm <- get_resource_map(mn, packageId)
aggregated_ids <- some_function_I_wrote_to_do_this(rm)
other_entity_ids <- some_function_I_wrote_to_do_this(otherEntities)

sd <- setdiff(aggregated_ids, other_entity_ids)
status <- length(sd== 0)

if (!status) {
  message <- paste0("There was a mismatch between the aggregated ids in the ORE and the EML: Aggregated vs otherEntity: ", sd, ".")
```

**Comment by leinfelder** [comment]
Sounds like we  are okay without supporting/encouraging the running of a suite _directly_ over an ORE object. A check is certainly welcome to locate the associated ORE (by searching a repo for it?) and then validate it with the metadata doc that it is processing.
