### ISSUE TITLE
Write up a draft Arctic Data Center Suite

### ISSUE THREAD

**Issue by amoeba** [NCEAS/mdqengine#40]
Write up a Suite for the Arctic Data Center.

**Comment by amoeba** [comment]
@mbjones wrote this up and I added the last two. What else?

# Arctic Data Center Quality Suite

- Identification
    - Identifier present
    - Identifier is DOI
    - Title is present
    - Title is sufficient
    - NSF award numbers present
    - Creator present
    - Creator has ORCID, email, address
    - Contact present
    - Contact has ORCID, email, address
    - Usage rights is either CC-0 1.0 or CC-BY 4.0
- Discovery
    - Abstract greater than 100 words
    - Keywords present
    - Temporal coverage has start year
    - Geographic coverage description present
    - Geographic coverage has coordinates
    - Taxonomic coverage is present
- Interpretation and Use
    - Method step present
    - Extent of Study Description
    - Sampling description present
    - All data entities described
        - Entity name, description, format, size, checksum
        - Attribute List
            - Attribute name differs from attribute description
            - Attribute description sufficient
            - Units defined
            - Missing value codes defined
            - Enumerated codes defined
- Data congruency
    - Attribute counts agree
    - Data format matches
    - Checksum matches data
    - Size matches
    - Attribute units sensible
    - Coded values all defined
    - Package manifest agrees with science metadata
- Informational
    - Data head and tail display
    - Outlier plots
- Data formats
  - Data objects are in non-proprietary formats
  - Data objects do not have funky stuff like margin calculations
- Miscellaneous (move items from this list into other headers as appropriate):
  - Metadata document is schema valid

**Comment by amoeba** [comment]
Using a Google Doc to organize this: https://docs.google.com/spreadsheets/d/1771E8b5PbnyBKKtYYaz-D4GeTqO2WwONI5LndaECe1s

**Comment by amoeba** [comment]
We decided on call to target a draft of this for 1.0 and a 'final' for 1.1.

**Comment by leinfelder** [comment]
I've switched the MetacatUI over to use this suite rather than the LTER one. I have concerns that the `check_presence` check in the metadig R package expects that all values be lists and so every test fails right now.

**Comment by amoeba** [comment]
The above issue has been addressed in the `metadig` R package

**Comment by amoeba** [comment]
Whoops, sorry. Forgot to close this before I left. V1 draft is in 072503c961ff33e7d189892f8b30451a8b18f36f. Will improve the suite in #45.
