### ISSUE TITLE
Create repos for R and Py libs

### ISSUE THREAD

**Issue by amoeba** [NCEAS/mdqengine#43]

**Comment by amoeba** [comment]
@mbjones can you please do this? I don't have privs.

Candidate repo/package names....

- rmdqe
- pymdqe
- mdqehelpers-r
- mdqehelpers-python

**Comment by mbjones** [comment]
Done, but after discussion with @amoeba , named:

* metadig-r
* metadig-py

**Comment by leinfelder** [comment]
Hi, can you explain what these are for? Thaaaaaanks!

**Comment by amoeba** [comment]
Right now, we just did this because I wrote a [single helper function](https://github.com/NCEAS/metadig-r/blob/master/R/checks.R) but that helper function needed a test and at that point it became an R package and somewhere in there it started to feel wrong to have it inside the `mdqengine` repo.

**Comment by gothub** [comment]
@amoeba You had mentioned on our call this week that having the R and Python libraries
in separate repos also provide:

- the ability to release check library versions independent of mdq releases
- assist in developing tests locally
