### ISSUE TITLE
Finish adding the LTER checks to the suite Google Doc

### ISSUE THREAD

**Issue by amoeba** [NCEAS/mdqengine#46]

**Comment by gothub** [comment]
The [google](https://docs.google.com/spreadsheets/d/1771E8b5PbnyBKKtYYaz-D4GeTqO2WwONI5LndaECe1s/edit#gid=0) now has an entry for each check from the LTER/PASTA suite.

**Comment by amoeba** [comment]
Great, thanks @gothub
