### ISSUE TITLE
Provide check scripts with any valid XPath return type

### ISSUE THREAD

**Issue by gothub** [NCEAS/mdqengine#5]
Currently the value returned from a check selector is the string equivalent of the value of the 
Xpath expression. This is fine for Xpath expressions that return nodes e.g.

```
//attributeList/attribute/attributeName
```

For Xpath selectors that express a different type, for examples 'boolean", is it feasible to pass  boolean and numeric values to the check script, so that the check  script doesn't have to convert from a string to the desired type? For example, for the selector

```
boolean(/eml/dataset/coverage/geographicCoverage)
```

the string value 'true' is passed to a Python script. Could this value instead be passed to
the Python script as a Python boolean value. The Java Xpath package does return different types, i.e. from https://docs.oracle.com/javase/7/docs/api/javax/xml/xpath/package-summary.html:

```
While XPath expressions select nodes in the XML document, the XPath API allows the selected nodes to be coalesced into one of the following other data types:

Boolean
Number
String
```

**Comment by leinfelder** [comment]
I'm not recasting types from strings to one of the following if applicable: int, float, boolean, string. Will depend on the scripting environment that is receiving them, but for python it seems to work well.
