### ISSUE TITLE
Proposal: Support multiple outputs per check in the web UI

### ISSUE THREAD

**Issue by amoeba** [NCEAS/mdqengine#53]
@gothub just wrote [another check](https://github.com/NCEAS/mdqengine/blob/master/src/main/resources/checks/creator.has.orcid.xml) which produces multiple text outputs. When we look at the web UI's rendering of a result that uses this Check, we see the three outputs concatenated onto one line, like

> A 'creator/userId' element not present, can not check for an ORCID A 'creator/electronicMailAddress' is present A 'creator/address' element is not present 

I think the display of it could be improved. See the [info section of this result page](https://mn-demo-8.test.dataone.org/metacatui/#mdq/s=arctic.data.center.suite.1/arctic.1.1) for a live example.

When Checks produce multiple outputs, it seems like the web UI could produce a richer display of them, perhaps as a bulleted list that is indented from the main list item. However, now that we've changed the display of Result to show the output first, I'm not sure what this should look like.

Currently, it's:

- A 'creator/userId' element not present, can not check for an ORCID A 'creator/electronicMailAddress' is present A 'creator/address' element is not present 
- Creator has ORCID FAILURE INFO identification
- The creator field should contain an ORCID, email and address. 

It might suffice just to throw each output in a block-level tag so it looks like:

- A 'creator/userId' element not present, can not check for an ORCID 
    
  A 'creator/electronicMailAddress' is present 

  A 'creator/address' element is not present 
- Creator has ORCID FAILURE INFO identification
- The creator field should contain an ORCID, email and address. 

Thoughts? I'm interested in what others think.

**Comment by leinfelder** [comment]
each output is now in it's own div
