### ISSUE TITLE
selectPath() doesn't use subSelector if result node list == 1

### ISSUE THREAD

**Issue by gothub** [NCEAS/mdqengine#6]
The following selector works correctly for a metadata document that has > 1 dataTables (e.g. knb-lter-sbc-1001-7.xml) but does not work if the result of the 'main' selector == 1, i.e. for a metadata document has 1 dataTable (e.g. knb-lter-sbc.18.18.xml):

```
		<selector>
			<name>attributeNames</name>
			<xpath>/eml/dataset/dataTable</xpath>
			<subSelector>
				<name>attributeNamesSubSelector</name>
				<xpath>./attributeList/attribute/attributeName</xpath>
			</subSelector>
		</selector>
```

It looks like XMLDialect.selectPath() checks the number of nodes returned from the 'main' 
xpath and if that is 1 then the text value is returned and the subSelector is not considered.
For this example selector, this node is not a leaf node, but there is only one of them in the metadata document "knb-lter-sbc.18.18.xml", so maybe a better check for selectPath() to make is to see if a subSelector is defined, and apply that to the result from the 'main' selector, regardless of result count.

**Comment by leinfelder** [comment]
I didn't see this until now. I'm pushed a change (and beefed up the unit test) to support this. I tried to add it to your LTER unit test, but it failed there. Not familiar enough with that suite to know where to start looking.
