### ISSUE TITLE
Test Arctic Date Center Suite against manually entered record

### ISSUE THREAD

**Issue by gothub** [NCEAS/mdqengine#61]
Use the Arctic data form to enter as complete as possible metadata record and 
check against the Arctic Data Suite. The user should be able to enter a record
that scores very well with the suite..

**Comment by gothub** [comment]
The quality check for manually entered metadata can be viewed [here](https://test.arcticdata.io/#mdq/arctic-data.40.3). 

Of the 3 failed checks:
- I think that the first and second checks should be set as 'INFO' type, as the registry form
doesn't allow a user to enter an entity description or attributes.
- The second check appears to have a bug that doesn't obtain the entity name correctly, which I will fix.

The INFO section has failed checks that may pass for other datasets, so should stay in.

**Comment by amoeba** [comment]
Totally agree with your comments. 👍

**Comment by gothub** [comment]
Check levels have been changed according to feedback from the dev team, last check level
change made in commit 265b83c4c3c235f234f219ffc27b0ec653ad3c76
