### ISSUE TITLE
See what's up with the NSF award database check

### ISSUE THREAD

**Issue by amoeba** [NCEAS/mdqengine#64]
On call today we noticed the nsf award check on https://test.arcticdata.io/#mdq/arctic-data.40.4 looked like it should've found an award. Check that the check is working as intended.

I think it might have needed to pad the number, e.g.,
https://www.nsf.gov/awardsearch/showAward?AWD_ID=0076039

**Comment by gothub** [comment]
The check ./checks/nsf.award.number.in.db.xml now zero pads the award number if necessary, fixed in commit b7c075a2bf874cc73c16426f4f71e99183adb760
