### ISSUE TITLE
Add parameters to checks

### ISSUE THREAD

**Issue by gothub** [NCEAS/mdqengine#7]
Providing a way to add parameters to a check definition would be very helpful, so that checks
could be modified without changing code. An example might be for a test that checks entity
name length, for which a parameter of the length to check could be in the check definition as:

```
<check>
...
<parameter>
   <name>entityNameLength</name>
   <type>integer</type>
   <value>40</value>
</parameter>
...
</check>
```

The mdqe would define the variable for appropriate scripting language. Not sure what the
best way to define the <type> as, because each scripting language will have it's own set of 
types.

**Comment by leinfelder** [comment]
I actually think you can accomplish this with a selector:

`<selector>
	<name>entityNameLength</name>
	<xpath>number("40")</xpath>
</selector>`

**Comment by leinfelder** [comment]
I think it's okay to either use the selector, or just have some constants in the beginning of your code

**Comment by gothub** [comment]
@leinfelder Yes, agreed. Initially I was thinking that being able to alter parameters of a check
should be easy to do, e.g.. changing the number of words required for an `<abstract>` to be valid, but now realize that changing the behaviour of a check shouldn't be so dynamic - i.e. a check should work the same for everyone and also be stable over time.
