### ISSUE TITLE
Suggestion: Changes to <dialect> elements of <check>

### ISSUE THREAD

**Issue by amoeba** [NCEAS/mdqengine#8]
Looking at at how the dialect test is currently implemented, I have some questions and ideas.

```{xml}
<suite>
        ...
	<check>
        ...
		<dialects>
			<name>eml</name>
			<xpath>boolean(/*[local-name() = 'eml'])</xpath>
		</dialects>
...
```
- Is my understanding correct that we implemented the `<dialect>` element as a way to automatically fail or skip the test if the dialect check doesn't pass? "I don't care what you have in your document, you fail/skip no matter what."
- Is this just a way of being explicit about skip conditions versus implicit, where the `<selector>` failing to match something is implicit and a `<dialect>` element is explicit?
- What are we doing when the dialect check fails, are we skipping or failing the check?

## Ideas
- dialect<->xpath map provided by the suite one time per suite as opposed to many times

```{xml}
<suite>
  ...
	<dialects>
		<name>eml</name> <!-- defined at the suite level -->
		<xpath>boolean(/*[local-name() = 'eml'])</xpath>
	</dialects>
  ...
  <check>
    ...
    <dialect>
      <name>eml</name> <!-- references suite-level definition -->
    </dialect>
    <dialect>
      <name>some_custom_dialect</name> <!-- custom dialect -->
      <xpath>boolean(...)</xpath>
    </dialect>
    ...
  </check>
  ...
</suite>
```

- Notes:
  - A suite doesn't have to use this facility and can instead define all <dialect> elements as we currently do, in each check

- Benefits: 
  - Less work for check writer
  - Lower chance for typos
  - Information about dialects contained within the suite (still)

- dialect<->xpath map provided by the mdqengine with non-supported dialects specified either at the suite level or check level

```{xml}
<suite>
  ...
  <check>
    ...
    <dialect>
      <name>eml</name> <!-- references a dialect defined by the mqe -->
    </dialect>
    ...
  </check>
  ...
</suite>
```

Dialects we don't provide mappings for would still be supported.

- Benefits:
  - Even less for the user to enter
- Downsides: 
  - This removes some of the information necessary to understand a suite

I put my vote in for at least abstracting the <dialect> <name> and <xpath> elements out of each check to DRY up the suite XML. Any thoughts?

**Comment by leinfelder** [comment]
I like putting the dialect at the suite level. I don't like having MDQE "know" which dialects are allowed since as it stands now, you can use the engine with any XML metadata even if the MDQE has never heard of it.

**Comment by gothub** [comment]
The check writer needs to have control over which checks are valid for which dialects. The check writer currently has the following options:

- have no `<dialect>` entries for a check, in which case the software assumes all dialects are valid
   - this may be useful for checks that are dialect independant, like is a universal element such as 'title' being present
- specify specific dialects that can be validated by a check (missing dialects are skipped by engine)
   - e.g. LTER has a packageId naming convention - it doesn't really make sense to check this against other dialects that don't have this convention (but this is up to the discretion of the check writer)
   - this check should be counted as a 'skip' for ISO, not as a 'failure' (in this check writer's opinion)
- specify multiple dialects for a check and have the check SKIP on some condition
  - not sure the application of this yet, but this gives the checks flexibility!

**Comment by amoeba** [comment]
Sounds good to me. So what do you think of my proposal?

**Comment by gothub** [comment]
@amoeba Having a suite level `<dialect>` is fine with me, as long as check level `<dialect>` is still supported. Maybe if `<dialect>` is present at the suite level, then it overrides the check level.

My one concern is when running one suite against multiple dialects that there is a mechanism to
say that  certain checks aren't relevant for certain dialects - as I mentioned, the LTER packageId check isn't valid for ISO and should be skipped.

Howver, if the HDF, LTER and others (our metadata communities?) say that checks should just pass or fail (and not skip), then I think we can do without check level `<dialect>`, and just have the suite level.

**Comment by amoeba** [comment]
Well, what I suggested above was that each check still has to specify all of its `<dialect>` elements. This proposal just DRY's up the <check> element. And I also suggested that checks can specify the check-level dialect in my code block above.

That looks like it covers your concerns. Sound right?

**Comment by leinfelder** [comment]
I think having dialect[s] specified at the check level still makes the most sense and keeps the checks independent of their suite. 

I think there are cases where a suite will be a mix of applicable checks and not. All suites will probably have a "schemaValidation" check and I'd hate to see that check skipped because the suite was labeled and not applicable to the dialect (even though it was XML metadata).

I do see that it can look very redundant when you stack them all up in a suite (like the LTER sample), but again, I think there are cases where we will want to show how Suite A works well on Corpus A (was designed for it), marginally well on Corpus B (has some similar cross-walkable fields), and poorly for Corpus C (totally different metadata model form anything we know).

**Comment by leinfelder** [comment]
Upshot: I'd just as soon leave it as it is.

**Comment by gothub** [comment]
I agree with leaving the `<dialect>` at the check level. In order for any dialect to work with a check, you have to specify a `<selector>` for the dialect, thereby implicitly enabling the check for that dialect. Specifying `<dialect>` for a check makes the support for the dialect explicit, and well, clearer.

**Comment by amoeba** [comment]
Sounds good to me. Thanks for the good discussion!
