### ISSUE TITLE
Can't find 'python' script engine

### ISSUE THREAD

**Issue by gothub** [NCEAS/mdqengine#82]
I've been trying to run tests locally and for some reason the dispatcher can't find
the class for the python engine:

```
suite="src/main/resources/suites/ACDD_Use.xml"
doc="src/test/resources/test-docs/iso19139.xml"
java -jar target/mdqengine-1.1.0-SNAPSHOT-jar-with-dependencies.jar $suite $doc
```
produces the error
```
java.lang.RuntimeException: Python Engine not found on the classpath.
	at edu.ucsb.nceas.mdqengine.dispatch.Dispatcher.<init>(Dispatcher.java:144)
	at edu.ucsb.nceas.mdqengine.dispatch.Dispatcher.getDispatcher(Dispatcher.java:166)
	at edu.ucsb.nceas.mdqengine.processor.XMLDialect.runCheck(XMLDialect.java:191)
	at edu.ucsb.nceas.mdqengine.MDQEngine.runSuite(MDQEngine.java:114)
	at edu.ucsb.nceas.mdqengine.MDQEngine.main(MDQEngine.java:196)
```

The jython jar contents are included in `target/mdqengine-1.1.0-SNAPSHOT-jar-with-dependencies.jar`, so I'm not sure what the trouble is:

I've tried jython 2.7.0, and the latest 2.7.x (2.7.1-rc3). Has anyone else encountered 
this problem?

**Comment by scgordon** [comment]
No, my issue yesterday was different. Will start a new issue for it as I don't think it's related...?

**Comment by amoeba** [comment]
A clean checkout of the repo and a subsequent `mvn clean install` works fine here. Is that what you are running and having trouble?

**Comment by gothub** [comment]
I was using a method to run a single check that appears to not work anymore. Anyway, another
route that does work is something like this:

```
mvn exec:java -Dexec.mainClass="edu.ucsb.nceas.mdqengine.MDQEngine" -Dexec.args="/Users/slaughter/workspace/mdqengine/src/test/resources/test-docs/dev-test-suite.xml /Users/slaughter/Projects/Metadig/LTER/knb-lter-sbc.10.21.xml"
```
