### ISSUE TITLE
Can't find suite xml

### ISSUE THREAD

**Issue by scgordon** [NCEAS/mdqengine#83]
Yesterday after running this command I got the following error. When I checked I found the files where there. It's been a while since I tried to build and run the engine locally, but I used commands from my terminal history. Should I be writing this differently?

bear:mdqengine scgordon$ mvn exec:java -Dexec.mainClass="edu.ucsb.nceas.mdqengine.MDQEngine" -Dexec.args="</Users/scgordon/mdqengine/src/main/resources/suites/ACDD_Discovery.xml> </Users/scgordon/CrosswalksWorkflow/collections/DataOne/GLEON/EML/xml/04053-metadata.xml>"

INFO] Building mdqengine 1.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ mdqengine ---
java.io.FileNotFoundException: </Users/scgordon/mdqengine/src/main/resources/suites/ACDD_Discovery.xml> (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at edu.ucsb.nceas.mdqengine.MDQEngine.main(MDQEngine.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.487 s
[INFO] Finished at: 2017-06-26T16:02:35-06:00
[INFO] Final Memory: 20M/312M
[INFO] ------------------------------------------------------------------------

Then I looked in the directory:

bear:mdqengine scgordon$ cd src/main/resources/suites/
bear:suites scgordon$ ls
ACDD_Discovery.xml			HCLS-Version_Discovery.xml
ACDD_DiscoveryACDD_ISO_EML.xml		IEDA_Discovery.xml
ACDD_Use.xml				ISO-1_Access.xml
CMR-Collection.xml			ISO-1_Discovery.xml
CMR-Common.xml				ISO_CSW_CompletenessSuitesPY.xml
CMR-Granule.xml				ISO_Lineage_Understanding.xml
CSW_Discovery.xml			ISO_Quality_Understanding.xml
DCAT_Discovery.xml			ISO_Reference_Understanding.xml
DIF_Discovery.xml			ISO_UserFeedback_Understanding.xml
DataCite4_Discovery.xml			LTER_Completeness.xml
DataCite_Discovery.xml			SERF_Access.xml
Dryad-File.xml				UMM-Collection.xml
Dryad-Package.xml			UMM-Common.xml
ECHO_Discovery.xml			UMM-Granule.xml
ECS_Discovery.xml			UMM-Variable.xml
FGDC_Discovery.xml			WSDL_Access.xml
FGDC_Understanding.xml			arctic-data-center.xml
HCLS-Distribution_Discovery.xml		knb-suite.xml
HCLS-Summary_Discovery.xml		test-lter-suite.xml

**Comment by amoeba** [comment]
The first thing I notice is the format of the path you're specifying, specifically the `<` and `>`. Try without.

**Comment by scgordon** [comment]
Cheers
