### ISSUE TITLE
Suggestion: Implement a method for retrieving data once per suite

### ISSUE THREAD

**Issue by amoeba** [NCEAS/mdqengine#9]
This solves the problem where `n` checks in a suite want to use the bytes at a URL referenced in the metadata, such as an EML entity data URL and we don't want to make `n` calls to get the bytes. I think this is a likely enough problem to consider doing something about it. This would be a small issue for small requests but it's a problem as `n` and the size of requests goes up as it slows down suite runs and wastes a lot of resources.

Suggestion: Add a suite-level element that allows the check to define specify a set of URLs to fetch via XPATH. The check still needs to parse the bytes, like with a `read.csv` call in R.

- We want to be careful about name collisions
- We're sort of implementing globals variables here. Can we just abstract this to let checks define globals? Do we have a use for global variables yet?
- Would we freeze the suite-level objects so checks don't mutate them? What's the reasonable expectation from the check runner/user here? I could see it being confusing if checks mutate globals.

Benefits:

- Suites checking against the same URL multiple times would run faster
- Because the MQE would know about the URLs its going to make a request on ahead of time, it can fetch the requests in parallel (suites run faster)
- If we encode some knowledge about Metacat systems into the MQE, we could even replace the URL with a filepath to a local system and save time. e.g. `https://arcticdata.io/metacat/d1/mn/v2/resolve/X` could be translated to a local file path if the MQE was running on arctica. We wouldn't need to do this on a first-pass implementation (or ever).

## Example API

Given the (abridged) suite:

```{xml}
<suite>
  ...
  <objects> <!-- not a great name -->
    <names>//otherEntity/entityname</name> <!-- keys -->
    <xpaths>//otherEntity/physical/distribution/online/url</xpath> <!-- vals -->
  </objects>
    ...
  </check>
    ...
  </check>
  ...
</suite>
```

And given the following (abridged) EML:

```{xml}
<dataset>
  ...
  <otherEntity>
    <entityName>a.csv</entityName>
    <physical>
      ...
      <distrubution>
        <online>
          <url>http://example.com/a.csv</url>
        </online>
      </distribution>
    </physical>
  </otherEntity>
  <otherEntity>
    <entityName>b.csv</entityName>
    <physical>
      ...
      <distrubution>
        <online>
          <url>http://example.com/b.csv</url>
        </online>
      </distribution>
    </physical>
  </otherEntity>
</dataset>
```

The MQE exposes a dict-like name in each check with:

```
keys: [ "a.csv", "b.csv" ]
values [ << bytes of a.csv >>, << bytes of b.csv >> ]
```

which then, e.g in R, you would have a check called something like "all csv objects can be read":

```
<code><![CDATA[
  library(xml2)
  entities <- # get nodeset of entities
  formats <- # get nodeset of formats

  csv_entities <- entities[formats == "text.csv"]

  for(entity in csv_entities) {
    read.csv(objects[[entity]])
  }  
]]></code>
```

**Comment by amoeba** [comment]
- What happens when a URL doesn't return the bytes, like in the case of an HTTP 404?

**Comment by leinfelder** [comment]
My solution to this is to have an initial check (e.g., myLoadDataCheck) be the first in the suite and subsequent checks can use variables that are set up by it. This keeps the suite as a very simple container and keeps the heavy lifting in the check - both in terms of the code and the model.
