### ISSUE TITLE
Consider adding version tag to suite <id>

### ISSUE THREAD

**Issue by gothub** [NCEAS/mdqengine#96]
The  KNB and ArcticData suites have the convention of appending a version number to the <id> element of the suite, for example `<id>knb.suite.1</id>`. Consider adding these to all suites, for example `ACDD_Discovery.xml`. The main benefit of doing this is that the version of the suite installed on the quality server can be easily checked, for example:

```
https://quality.nceas.ucsb.edu/quality/suites
```

returns:
```
["ACDD_Discovery_ACDD_ISO","knb.suite.1","CSWCoreQueryablesISO","arctic.data.center.suite.1","test-lter-suite.1.1"]
```

Thoughts @scgordon?

**Comment by scgordon** [comment]
Yep, seems like a good idea and easy to implement. So what would be the convention for version numbers? just 1, 2, 3 or 1.1, 1.2, etc

**Comment by scgordon** [comment]
https://github.com/NCEAS/mdqengine/pull/98
